name: "pg-ldap-sync"

services:

  glauth:
    image: docker.io/glauth/glauth:v2.3.2
    ports:
      - "3893:3893"
    volumes:
      - ./tests/_configs/glauth.cfg:/app/config/config.cfg

  postgres:
    image: docker.io/postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
