# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
      - name: "Install binaries"
        run: |
          sudo apt update
          sudo apt install libldap2-dev
          sudo apt install libsasl2-dev
      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: "Install poetry & tox"
        run: |
          pipx install poetry
          pipx install tox
      - name: "Run linters"
        run: tox run -e lint

  test-unit:
    name: "Run unit tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
      - name: "Install binaries"
        run: |
          sudo apt update
          sudo apt install libldap2-dev
          sudo apt install libsasl2-dev
      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: "Install poetry & tox"
        run: |
          pipx install poetry
          pipx install tox
      - name: "Run tests"
        run: tox run -e unit
      - name: "Upload Coverage to Codecov"
        uses: codecov/codecov-action@v5

  test-integration:
    name: "Run integration tests"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - postgres: { version: "16" }
          - postgres: { version: "18" }
    env:
      GLAUTH_USERNAME: cn=serviceuser,ou=svcaccts,dc=glauth,dc=com
      GLAUTH_PASSWORD: dogood
      POSTGRES_DATABASE: postgres
      POSTGRES_USERNAME: postgres_ldap_sync
      POSTGRES_PASSWORD: postgres_ldap_sync
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
      - name: "Set up Compose"
        uses: docker/setup-compose-action@v1
      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: "Install binaries"
        run: |
          sudo apt update
          sudo apt install libldap2-dev
          sudo apt install libsasl2-dev
      - name: "Install poetry & tox"
        run: |
          pipx install poetry
          pipx install tox
      - name: "Start services"
        run: docker compose -f compose/postgresql-${{ matrix.postgres.version }}.yaml up --wait
      - name: "Run tests"
        run: tox run -e integration
      - name: "Stop services"
        run: docker compose -f compose/postgresql-${{ matrix.postgres.version }}.yaml down
      - name: "Upload Coverage to Codecov"
        uses: codecov/codecov-action@v5
