# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.
name: Publish PPA

on:
  push:
    tags:
      - "*"

env:
  DEBEMAIL: data-platform@lists.launchpad.net
  DEBFULLNAME: Data Platform
  DEBSIGN_KEY: ${{ secrets.GPG_PRIVATE_KEY }} # Expires 2028-03-12
  DEBSIGN_KEYID: ${{ secrets.GPG_PRIVATE_KEY_ID }}

jobs:
  publish-ppa:
    name: "Publish to PPA"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Install binaries"
        run: |
          sudo apt update
          sudo apt install build-essential
          sudo apt install devscripts
          sudo apt install dh-make
          sudo apt install dh-python
      - name: "Install poetry"
        run: pipx install poetry
      - name: "Export package information"
        run: echo "VERSION=$(poetry version --short)" >> "$GITHUB_ENV"
      - name: "Create Debian changelog"
        run: |
          dch --create \
            --package postgresql-ldap-sync \
            --newversion ${{ env.VERSION }}
      - name: "Download latest version"
        run: uscan --download-current-version
      - name: "Create Debian patch"
        run: |
          dpkg-source --commit \
            --diff-ignore=".git|.github|tests|\.ini|\.lock|\.yaml" \
            . Files
      - name: "Import GPG key"
        run: |
          echo "${GPG_PRIVATE_KEY}" | gpg --batch --quiet --import
      - name: "Build Debian package"
        run: |
          dpkg-buildpackage -sa \
            --no-check-builddeps \
            --build=source \
            --force-sign
      - name: "Upload to PPA"
        run: |
          dput ppa:data-platform/postgresql-ldap-sync \
            ../postgresql-ldap-sync_*_source.changes
