# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.
name: Publish PYPI

on:
  push:
    tags:
      - "*"

jobs:
  publish-pypi:
    name: "Publish to PyPI"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Install poetry"
        run: pipx install poetry
      - name: "Build package"
        run: poetry build
      - name: "Upload to PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
    permissions:
      id-token: write
